### PR TITLE
New mlpack website

### PR DESCRIPTION
**Pull request by rcurtin**
I've been working on this for quite a while now; it turns out getting the documentation and Doxygen documentation to generate automatically was quite time-consuming to get right.  So, here it is:

http://orange.ratml.org:4000/mlpack/

It's probably not worth reading the diff for this, since it's a lot of bash scripts, removing old things, and adding new things.

Please let me know any problems that you find.  Otherwise I'll merge this in after a few days.  @zoq @ShikharJ your comments would be appreciated if you are interested (anyone else's comments are of course welcome too).

I think this will make the site a lot easier to maintain, and most importantly, it'll make it way, way easier to update the website when a new release is ready.  In fact with the scripts in `_src/`, it should just be:

```
$ cp mlpack-a.b.c.tar.gz _src/
$ _src/scripts/build-version.sh a.b.c
... wait a while ...
$ _src/scripts/rebuild-docs.sh
$ jekyll b
```

(For comparison, before I had to edit each HTML file individually and it could take 45 minutes to an hour of work.)

### CODE REVIEW

**Comment by manish7294** [comment]
Hi @rcurtin, that's really impressive upgrade. Everything seems neat. And I should say, I totally loved the organization & presentation of documentation. Moreover, color contrast is more appealing now. But I have notice some broken links, majorly on Home page (thought I suspect you may be working over those parts), also Github redirect link in navigation tab seems to be broken.

**Comment by zoq** [comment]
Wow, really nice work, as @manish7294 already pointed out there are a couple of links that aren't working, should I list them here?

Do you think we could use the same color scheme as for the home page for the documentation as well? The white is super bright.

home:

screen_A

documentation:

screen_B

**Comment by rcurtin** [comment]
Thanks for the comments, guys. :+1:  I fixed many links and the CSS issues (I thought I'd removed all the `#fff` but it looks like there are a few places I missed).  I made some fixes to the scripts, but it will take a little while for the website to rebuild (all the Doxygen paths were wrong, so it has to rebuild all the Doxygen versions).  Should be done in about 12 hours (it takes a little while to run, my Doxygen postprocessing scripts are not efficient...).

**Comment by zoq** [comment]
Still in the build process?

**Comment by rcurtin** [comment]
Yeah, still debugging some things... I'll post a comment when I have it built right...

**Comment by AYESDIE** [comment]
Hi, The new website looks cool :D and the contrast looks nice.
I wanted to point some issues tho.
- Long method names gets cropped on the left side bar on the documentation page. It only happens with `mlpack_local_coordinate_coding` as of now.
image

- I also noticed that the webpage was for mobile device too ( ͡° ͜ʖ ͡°). But there was an issue here.
image
Any of the link here was redirecting to `page not found` page. This was one of the link `http://orange.ratml.org:4000/community.html.html`. The reason was every single one of them had `.html.html` in the end.

**Comment by rcurtin** [comment]
Ok, I managed to get everything to regenerate right.  So at least I shouldn't need to build the Doxygen documentation again, making lots of other fixes much quicker. :)

@ayesdie thanks for taking a look.  The mobile version is the same as the ensmallen mobile website.  I forgot to test it so I am surprised it works ok. :)  I'll look into the issues there (also there is no "documentation" link there so I'll have to put that there); I think it should be a simple Jekyll fix.  I'll also widen the sidebar a bit and that should solve the overflow issue.

**Comment by KimSangYeon-DGU** [comment]
Wow!! I like it. It's very nice!!! :+1: x 100000

**Comment by zoq** [comment]
Looks like I can't comment on the diff since it's too big for Github. I'll use the comment section:

Home
- The armadillo doesn't work, probably because the armadillo page doesn't support https.
- I think for ensmallen it might be useful to link to the https page.
- mlpack command-line quickstart guide  links to the latest stable version, but the version selector shows mlpack-git

Command-line quickstart page
- The item color of the version selector is difficult to see:

quickstart


questions page:
- I think it would be great to highlight the citation more, right now it more or less blends over with the main text.

**Comment by rcurtin** [comment]
Thanks for the comments, I'll try to address them tonight.  The quickstart guide doxygen is fixed, but I'm still rebuilding the documentation (I couldn't last night because I was running some simulations on all cores...).

> The item color of the version selector is difficult to see:

You're right.  What about the version selector on the main documentation page?  Is that styled better?  If so I'll just copy over the CSS for that.

**Comment by zoq** [comment]
> You're right. What about the version selector on the main documentation page? Is that styled better? If so I'll just copy over the CSS for that.

Yes, it's white on black at least in Firefox. In Chrome the current solution looks fine for both cases.

**Comment by rcurtin** [comment]
Ok, I think that everything is ready here.  Let me know if anyone has any other comments, otherwise I'll merge it in 3 days or so and deploy the new website.

**Comment by zoq** [comment]
Some more notes:

- the Github link doesn't work
- the reference on the GSoC page doesn't work
- do you think we should change the representation of the non-existing default value, looks like currently, it's ``**--**``; here is an example:

docs_default

**Comment by rcurtin** [comment]
I was going to do the Github link as an Apache redirect, but actually it's not too hard to do it natively in Jekyll (and then the URL makes far more sense too).

The `**--**` was meant to be a placeholder for something that was required (I guess I likely meant `*--*` or `***--***`).  But in any case I think it looks better as `***required***` so I changed it in some postprocessing scripts.  I'll open a PR for the Markdown bindings to make this small change.

I fixed the links on the `gsoc.md` page too.

**Comment by zoq** [comment]
Thanks for the clarification, personally I think it's much cleaner now.

**Comment by rcurtin** [comment]
Thanks everyone.  Let's see how much of a disaster it is when I try to merge and deploy this. :)

**Comment by rcurtin** [comment]
If anyone has more comments we can just open them as separate issues.

**Pull request merged**
