### PR TITLE
Updating getstarted page for macOS users.

### PR DESCRIPTION
**Pull request by qureshinomaan**
Trying to resolve #2137

### CODE REVIEW

**Comment by zoq** [comment]
I'll let this open as I think @rcurtin has to manually trigger the build process.

**Comment by rcurtin** [comment]
Ok, updated: https://www.mlpack.org/getstarted.html :+1:

**Comment by qureshinomaan** [comment]
Hey @rcurtin @zoq 
Thanks. It feels nice to have finally contributed something!!.
A minor style fix. Sorry for the inconvenience.
https://github.com/mlpack/mlpack.org/pull/23

**Comment by rcurtin** [comment]
It is not an inconvenience at all to have you help out!  Please feel free. :)

**Pull request merged**
