### PR TITLE
Added Favicon icon

### PR DESCRIPTION
**Pull request by gauravghati**
Added as per [#2799](https://github.com/mlpack/mlpack/issues/2799).
I haven't tested it locally. I guess it should work. Please verify before merging.

### CODE REVIEW

**Comment by UmarJ** [comment]
Works on my end.

**Comment by zoq** [comment]
I think it makes sense to also have `favicon.ico` in `/html` this should also cover pages which don't specific the icon.

**Comment by gauravghati** [comment]
> I think it makes sense to also have `favicon.ico` in `/html` this should also cover pages which don't specific the icon.

done, should I change the href from  `static/img/mlpack-logo.svg` to `favicon.ico` in HTML pages?

**Comment by zoq** [comment]
> > I think it makes sense to also have `favicon.ico` in `/html` this should also cover pages which don't specific the icon.
> 
> done, should I change the href from `static/img/mlpack-logo.svg` to `favicon.ico` in HTML pages?

I think it's fine.

**Review by zoq — APPROVED** [review]
Thanks for putting this together.

**Comment by zoq** [comment]
Thanks again.

**Pull request merged**
